version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - djangoproject_network
    volumes:
      - djangoproject_static:/data/static/
      - djangoproject_media:/data/media/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: djangoproject:4
    networks:
      - djangoproject_network
    volumes:
      - djangoproject_static:/home/git_1ban_web/staticfiles/
      - djangoproject_media:/home/git_1ban_web/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - djangoproject_network
    volumes:
      - djangoproject_mariadb:/var/lib/mysql/
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: asdf1234!
      MARIADB_ROOT_PASSWORD: asdf1234!

networks:
  djangoproject_network:

volumes:
  djangoproject_static:
  djangoproject_media:
  djangoproject_mariadb: